[package]
name = "dogrec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
reqwest = "0.11.14"
serde_json = "1.0.93"
actix-web = "4"
rand = "0.8"
csv = "1.1"